---
title: "[F-Lab 모각코 챌린지] 34일차"
excerpt: "Promise"
categories:
  - Javascript
tags:
  - f-lab
  - 에프랩
  - TIL
  - Javascript
  - Promise
last_modified_at: 2023-06-22
toc: true
---

최근 콜백 함수와 콜백 지옥에 대해 알아봤다. 콜백 함수를 사용하지 않고 비동기 처리를 할 순 없을까? 오늘 배울 `Promise`가 그런 역할을 해준다!

# Promise ?

`Promise`는 비동기 작업의 최종 완료 혹은 실패를 나타내는 객체이다. 프로미스를 사용하면 비동기 메서드에서 마치 동기 메서드처럼 값을 반환할 수 있다. 다만 최종 결과를 반환하는 것이 아니고, 미래의 어떤 시점에 결과를 제공하겠다는 '약속'(프로미스)을 반환한다.

일단 어떻게 사용하는지부터 알아보자.

```javascript
let promise = new Promise(function (resolve, reject) {
  // 비동기 작업(함수)
});
```

이렇게 `new` 연산자를 사용해 `promise` 객체를 만든다. 그리고 생성자 함수에 전달되는 함수를 실행 함수라고 부르는데, `new Promise`가 만들어질 때 자동으로 실행된다. 그리고 인자로 `resolve` 와 `reject` 함수를 받는데, 얘네는 자바스크립트에서 자체 제공하는 콜백이다. 그리고 비동기 작업 이후에 둘 줄 하나를 반드시 호출해야 한다.

- `resolve(value)`: 비동기 작업이 성공적으로 끝난 경우 그 결과를 인자로 담아 호출.
- `reject(error)`: 에러 발생 시 에러 객체를 나타내는 `error`를 인자로 담아 호출

`new Promise` 생성자가 반환하는 `promise` 객체는 아래와 같은 내부 프로퍼티를 갖고 있다.

- `state`: 처음엔 "pending"(보류)였다가 `resolve`가 호출되면 "fulfilled", `reject`가 호출되면 "rejected"로 변한다.
- `result`: 처음엔 undefined였다가 `resolve(value)`가 호출되면 value로, `reject(error)`가 호출되면 error로 변한다.

![promise의 상태](https://ko.javascript.info/article/promise-basics/promise-resolve-reject.svg)

아래의 예시를 보자.

```javascript
let promise = new Promise(function (resolve, reject) {
  // 프라미스가 만들어지면 이 부분은(실행 함수) 자동 실행

  // 1초 뒤에 일이 성공적으로 끝났다는 신호가 전달되면서 result는 '완료'가 되며, state는 fulfilled가 된다.
  setTimeout(() => resolve("완료"), 1000);
});
```

만약 실행 함수가 실패한다면?

```javascript
let promise = new Promise(function (resolve, reject) {
  // 이 경우 result는 Error 객체가 되고, state는 rejected가 된다.
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});
```

실행 함수는 반드시 `resolve`나 `reject`중 하나를 호출해야 한다. 만약 둘 다 호출된다면 먼저 호출된 상태만 반영된다. 이렇게 `resolve`나 `reject` 된 프라미스를 settled promise 라 부른다.

# 어떻게 사용해?

여기까진 비동기 작업이 실행되었을 뿐이다. 하지만 우리가 해야할 건 비동기 작업을 제어하는 것이다.

## then

`then`은 프라미스에서 가장 중요한 메서드다. 왜냐하면 비동기 작업 이후 받아온 결과를 가지고 작업할 수 있기 때문이다. `then`의 첫 번째 인수는 실행 함수에서 `resolve`가 호출되었을 때 실행되는 함수이고, 두 번째 인수는 `reject` 되었을 때 실행되는 함수다. 아래의 예제를 보자.

```javascript
let promise = new Promise(function (resolve, reject) {
  setTimeout(() => resolve("완료!"), 1000);
});

// resolve 함수는 .then의 첫 번째 함수(인수)를 실행
promise.then(
  (result) => alert(result), // 1초 후 "완료!"를 출력
  (error) => alert(error) // 실행되지 않음
);
```

에러가 발생한 경우만 다루고 싶다면, `then`메서드의 첫 번째 인자에는 `null`을, 두 번째 인자에는 result로 받을 error를 핸들링 할 함수를 쓰면 된다. `then(null, errorHandling)`

## catch

`then(null, errorHandling)` 대신 에러가 발생한 경우만 다루고 싶다면 `catch`를 쓰면 된다.

```javascript
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
```

`then`과 `catch`를 같이 쓸 수도 있다. 우리는 비동기 작업이 성공여부를 장담할 수 없다. 그러니 아래와 같이 작성하는 게 맞을 것이다.

```javascript
const promise = new Promise((resolve, reject) => {
  // 비동기 작업

  if (/* 비동기 작업 수행 성공 */) {
    resolve('result');
  }
  else { /* 비동기 작업 수행 실패 */
    reject('failure reason');
  }
});

promise
  .then(res => console.log(res))
  .catch(err => console.error(err));
```

## finally

`finally`는 결과가 어떻든 실행된다. `try {...} catch {...}` 의 finally와 유사하다. 사용법도 위의 `then`과 비슷하다.

```javascript
new Promise((resolve, reject) => {
  /* 비동기 작업, 그 후 resolve, reject를 호출 */
})
  // 성공·실패 여부와 상관없이 프라미스가 처리되면 실행됨
  .finally(() => 로딩 인디케이터 중지)
  .then(result => result와 err 보여줌 => error 보여줌)
```

보는것 처럼 `then`과는 약간의 차이가 있는데, 첫째로 인수가 없다. 둘째로 `finally`는 자동으로 다음 핸들러에 결과와 에러를 전달한다. `finally` 이후에 `then`이 온 것을 주목하자.

\*참고: <https://ko.javascript.info/promise-basics>,  
<https://poiemaweb.com/es6-promise>,
