---
title: "2023.11.18 til"
excerpt: "오늘 배운 모든 내용"
categories:
  - til
tags:
  - javascript
last_modified_at: 2023-11-18
toc: true
---

# axios

Ajax 통신을 위해 가장 많이 사용되는 패키지인 axios에 대해 알아보자.

axios 객체에서 리퀘스트를 보내는 많은 메소드들이 fetch 함수처럼 Promise 객체를 리턴한다. 다음 코드를 보자.

```js
axios
  .get("https://jsonplaceholder.typicode.com/users")
  .then((response) => {
    console.log(response);
  })
  .catch((error) => {
    console.log(error);
  });
```

`axios.get`이라고 쓰여 있는 부분만 fetch로 바꾸면 fetch 함수와 사용법이 비슷하다.  
다만, axios 객체에는 fetch 함수에는 없는 다음과 같은 몇 가지 기능 및 장점들이 있다.

- 모든 리퀘스트, 리스폰스에 대한 공통 설정 및 공통된 전처리 함수 삽입 가능
- serialization, deserialization을 자동으로 수행
- 특정 리퀘스트에 대해 얼마나 오랫동안 리스폰스가 오지 않으면 리퀘스트를 취소할지 설정 가능(request timeout)
- 업로드 시 진행 상태 정보를 얻을 수 있음
- 리퀘스트 취소 기능 지원

# async/await

async와 await는 promise를 더 쉽게 다루기 위한 연산자이다. 다음 코드를 보자.

```js
// fetch("https://jsonplaceholder.typicode.com/users")
//   .then((response) => response.text())
//   .then((result) => {
//     console.log(result);
//   });

async function fetchAndPrint() {
  const response = await fetch("https://jsonplaceholder.typicode.com/users");
  const result = await response.text();
  console.log(result);
}

fetchAndPrint();
```

`fetchAndPrint` 함수는 주석처리 된 부분과 동일하게 동작한다. 함수 선언 부분에 `async` 키워드를 붙혔고, 함수 내부에서 promise 객체를 반환하는 메서드 앞에 `await`를 붙혀줬다.  
`async`는 asynchronous의 줄임말로, 비동기를 의미한다. 이 키워드는 함수 내에 비동기적으로 실행될 부분이 있다는 것을 의미한다. `await` 이 붙어있는 코드가 그것이다.  
`await`은 '~을 기다리다' 라는 의미다. `await`은 그 뒤의 코드를 실행하고 코드가 리턴하는 promise 객체가 fulfilled 혹은 rejected 상태가 될 때까지 기다려준다. promise 객체가 fulfilled 되면 그 작업 결과를 리턴한다. 만약 Promise가 reject되면, reject된 값을 throw한다. 또, await 연산자 뒤의 코드가 Promise가 아니면 해당 값을 resolved Promise로 변환시킨다. 참고로 `await`은 `async` 함수 내부에서만 사용할 수 있다(그렇지 않으면 SyntaxError).

## async/await의 실행 순서

```js
async function fetchAndPrint() {
  console.log(2);
  const response = await fetch("https://jsonplaceholder.typicode.com/users");
  console.log(7);
  const result = await response.text();
  console.log(result);
}

console.log(1);
fetchAndPrint();
console.log(3);
console.log(4);
console.log(5);
console.log(6);
```

위 코드는 콘솔에 찍히는 순서대로 실행된다. async 함수는 await 키워드를 만나면 Call stack 에서 빠져나와 실행되지 않은 나머지 부분은 Microtask Queue에 적재된다.

## async/await reject 처리

```js
async function fetchAndPrint() {
  const response = await fetch("https://jsonplaceholder.typicode.commmm/users");
  const result = await response.text();
  console.log(result);
}

fetchAndPrint();
```

이렇게 없는 url을 fetch문에 넣으면 결국 rejected 상태의 Promise 객체가 제대로 처리되지 않았기 때문에 에러가 뜬다.  
promise 체이닝에서는 catch 메서드를 사용했는데, async/await을 사용할 때는 try/catch문을 사용한다.

```js
async function fetchAndPrint() {
  try {
    const response = await fetch(
      "https://jsonplaceholder.typicode.commmm/users"
    );
    const result = await response.text();
    console.log(result);
  } catch (error) {
    console.log(error);
  }
}

fetchAndPrint();
```

이렇게 작성하면 try 블록 안에서 await이 붙어있는 promise 객체들중, rejected 상태가 된 것이 생기면, 그 순간 코드의 흐름이 catch문으로 넘어오게 된다. 그리고 error 파라미터로 rejected된 promise 객체의 작업 실패 정보가 넘어오게 된다.  
finally 블록을 추가할 수도 있다.

```js
async function fetchAndPrint() {
  try {
    const response = await fetch(
      "https://jsonplaceholder.typicode.commmm/users"
    );
    const result = await response.text();
    console.log(result);
  } catch (error) {
    console.log(error);
  } finally {
    console.log("exit");
  }
}

fetchAndPrint();
```

finally 메서드와 마찬가지로 작업이 모두 잘 성공하든, 어떤 promise 객체가 rejected 되든 상관 없이 항상 finally 블록 안의 코드는 실행된다.

## async 함수는 항상 promise 객체를 리턴한다

```js
async function asyncFunc() {
  return 3;
}

asyncFunc();
```

여기서 호출된 `asyncFunc` 함수는 뭘 리턴할까? 그냥 3이 아니다.  
3을 작업 성공 결과로 가진 fulfilled된 promise 객체를 리턴한다.

async 함수는 그 안에서 리턴하는 값에 따라 그에 맞는 Promise 객체를 리턴한다. 이때 적용되는 규칙은 우리가 이전에 `then` 메소드의 규칙들과 유사하다.

1. 어떤 값을 리턴하는 경우
   1. Promise 객체를 리턴하는 경우
      : 해당 Promise 객체와 동일한 상태와 작업 성공 결과(또는 작업 실패 정보)를 가진 Promise 객체를 리턴한다.(그냥 해당 Promise 객체를 리턴한다고 봐도 된다.)
   2. Promise 객체 이외의 값을 리턴하는 경우
      : fulfilled 상태이면서, 리턴된 값을 작업 성공 결과로 가진 Promise 객체를 리턴한다.
2. 아무 값도 리턴하지 않는 경우
   : undefined를 리턴한 것으로 간주해 fulfilled 상태이면서, undefined를 작업 성공 결과로 가진 Promise 객체가 리턴된다.
3. async 함수 내부에서 에러가 발생했을 때
   : rejected 상태이면서, 해당 에러 객체를 작업 실패 정보로 가진 Promise 객체가 리턴된다.

## async 함수 팁

```js
async function getResponses(urls) {
  for (const url of urls) {
    const response = await fetch(url);
    console.log(await response.text());
  }
}
```

이 코드는 await 문이 붙은 Promise 객체가 fulfilled 상태가 될 때까지는 그 다음 URL에 대한 작업들이 시작될 수 없기 때문에, 이전 URL에 리퀘스트를 보내고 리스폰스를 받아서 출력하고 나서야, 다음 URL에 대한 리퀘스트를 보낼 수 있다. 만약 모든 리스폰스의 내용이 잘 출력되기만 하면 되고, 그 순서는 상관없는 경우라면 이 코드는 성능 관점에서 아쉬운 점이 있는 코드이다.  
그럴 땐 코드를 이렇게 바꿔볼 수 있다.

```js
async function fetchUrls(urls) {
  for (const url of urls) {
    (async () => {
      const response = await fetch(url);
      console.log(await response.text());
    })();
  }
}
```

각 url에 리퀘스트를 보내고 리스폰스를 받는 코드를, 별도의 즉시실행되는 async 함수로 감싸줬다. 이렇게 코드를 고치면 일단 각 URL에 대해서 fetch 함수를 실행해서 리퀘스트를 보내는 것을 순서대로 바로 실행해버린다. 그러면 일단 모든 URL에 대한 리퀘스트를 쭉 보내버리고, 먼저 리스폰스가 오는 순서대로 그 내용이 출력된다.  
만약 순차적인 처리가 필요한 경우가 아니라면 방금 본 것처럼 각 작업을 다시 async 함수로 묶어주면 된다.
